kind = "mobile"
previewPath = "/expo/"
title = "Met"
version = "1.0.0"
id = "artifacts/met"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/expo/" ]
localPort = 25933

[services.development]
run = "pnpm --filter @workspace/met run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/met", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/met", "run", "serve" ]

[services.env]
PORT = "25933"
BASE_PATH = "/"
