// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/met-screens/EncountersNew.tsx": () => import("../components/mockups/met-screens/EncountersNew.tsx"),
  "./components/mockups/met-screens/HomeNew.tsx": () => import("../components/mockups/met-screens/HomeNew.tsx"),
  "./components/mockups/met-screens/OnboardingCurrent.tsx": () => import("../components/mockups/met-screens/OnboardingCurrent.tsx"),
  "./components/mockups/met-screens/OnboardingNew.tsx": () => import("../components/mockups/met-screens/OnboardingNew.tsx"),
  "./components/mockups/ads/ConnectionsAd.tsx": () => import("../components/mockups/ads/ConnectionsAd.tsx"),
  "./components/mockups/ads/EncountersAd.tsx": () => import("../components/mockups/ads/EncountersAd.tsx"),
  "./components/mockups/ads/ProfileAd.tsx": () => import("../components/mockups/ads/ProfileAd.tsx"),
  "./components/mockups/ads/RadarAd.tsx": () => import("../components/mockups/ads/RadarAd.tsx"),
  "./components/mockups/ads/RevealAd.tsx": () => import("../components/mockups/ads/RevealAd.tsx")
};
