// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/met-screens/EncountersNew.tsx": () => import("../components/mockups/met-screens/EncountersNew.tsx"),
  "./components/mockups/met-screens/HomeNew.tsx": () => import("../components/mockups/met-screens/HomeNew.tsx"),
  "./components/mockups/met-screens/OnboardingCurrent.tsx": () => import("../components/mockups/met-screens/OnboardingCurrent.tsx"),
  "./components/mockups/met-screens/OnboardingNew.tsx": () => import("../components/mockups/met-screens/OnboardingNew.tsx")
};
