// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ads/ChatAd.tsx": () => import("../components/mockups/ads/ChatAd.tsx"),
  "./components/mockups/ads/ConnectionsAd.tsx": () => import("../components/mockups/ads/ConnectionsAd.tsx"),
  "./components/mockups/ads/EncountersAd.tsx": () => import("../components/mockups/ads/EncountersAd.tsx"),
  "./components/mockups/ads/HeatmapAd.tsx": () => import("../components/mockups/ads/HeatmapAd.tsx"),
  "./components/mockups/ads/LeaderboardAd.tsx": () => import("../components/mockups/ads/LeaderboardAd.tsx"),
  "./components/mockups/ads/ProfileAd.tsx": () => import("../components/mockups/ads/ProfileAd.tsx"),
  "./components/mockups/ads/RadarAd.tsx": () => import("../components/mockups/ads/RadarAd.tsx"),
  "./components/mockups/ads/RevealAd.tsx": () => import("../components/mockups/ads/RevealAd.tsx"),
  "./components/mockups/met-ui-concepts/CyberSocial.tsx": () => import("../components/mockups/met-ui-concepts/CyberSocial.tsx"),
  "./components/mockups/met-ui-concepts/GamifiedModern.tsx": () => import("../components/mockups/met-ui-concepts/GamifiedModern.tsx"),
  "./components/mockups/met-ui-concepts/PremiumLifestyle.tsx": () => import("../components/mockups/met-ui-concepts/PremiumLifestyle.tsx"),
  "./components/mockups/met-screens/ChatShot.tsx": () => import("../components/mockups/met-screens/ChatShot.tsx"),
  "./components/mockups/met-screens/EncountersNew.tsx": () => import("../components/mockups/met-screens/EncountersNew.tsx"),
  "./components/mockups/met-screens/HeatmapShot.tsx": () => import("../components/mockups/met-screens/HeatmapShot.tsx"),
  "./components/mockups/met-screens/HomeNew.tsx": () => import("../components/mockups/met-screens/HomeNew.tsx"),
  "./components/mockups/met-screens/LeaderboardShot.tsx": () => import("../components/mockups/met-screens/LeaderboardShot.tsx"),
  "./components/mockups/met-screens/OnboardingCurrent.tsx": () => import("../components/mockups/met-screens/OnboardingCurrent.tsx"),
  "./components/mockups/met-screens/OnboardingNew.tsx": () => import("../components/mockups/met-screens/OnboardingNew.tsx"),
  "./components/mockups/met-screens/ProfileShot.tsx": () => import("../components/mockups/met-screens/ProfileShot.tsx"),
  "./components/mockups/venue-designs/BrightAiry.tsx": () => import("../components/mockups/venue-designs/BrightAiry.tsx"),
  "./components/mockups/venue-designs/CleanSlate.tsx": () => import("../components/mockups/venue-designs/CleanSlate.tsx"),
  "./components/mockups/venue-designs/WarmTerracotta.tsx": () => import("../components/mockups/venue-designs/WarmTerracotta.tsx")
};
