-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgiAL959bl9fbKxGyf
FsS1hEcykdFQHcvLcn4+G+zyLxygCgYIKoZIzj0DAQehRANCAATYmsN7DpyqTT+g
zx1D+A+69ih1BUDdpAU1wufIU6x71/Fiz2cwOk/yyPbMIiIAnLpzYH+cDmpvY7Hi
3uMyq4iM
-----END PRIVATE KEY-----