// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtUiT2uaRBGflANIODgYEZFFGR8gotSzQ',
    appId: '1:572463722097:web:88f24c96c1cad483f4f5d0',
    messagingSenderId: '572463722097',
    projectId: 'metapp-b4642',
    authDomain: 'metapp-b4642.firebaseapp.com',
    storageBucket: 'metapp-b4642.firebasestorage.app',
    measurementId: 'G-HSKB3Y1KEG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD63sbprh_Pi9kIsBRY-3cXT7vWbh-ArX8',
    appId: '1:572463722097:android:9c99ef7ec6afda3cf4f5d0',
    messagingSenderId: '572463722097',
    projectId: 'metapp-b4642',
    storageBucket: 'metapp-b4642.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIKGH3kMUp8uZtcglqrNN9kKxOAzB7Jt8',
    appId: '1:572463722097:ios:ac2bc20907623765f4f5d0',
    messagingSenderId: '572463722097',
    projectId: 'metapp-b4642',
    storageBucket: 'metapp-b4642.firebasestorage.app',
    androidClientId: '572463722097-d6nbe4fnfn45ulfk5ier26bg5i8prblm.apps.googleusercontent.com',
    iosClientId: '572463722097-t2au0ipl4t6b6atcck2043pkm9agldau.apps.googleusercontent.com',
    iosBundleId: 'com.example.metApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIKGH3kMUp8uZtcglqrNN9kKxOAzB7Jt8',
    appId: '1:572463722097:ios:ac2bc20907623765f4f5d0',
    messagingSenderId: '572463722097',
    projectId: 'metapp-b4642',
    storageBucket: 'metapp-b4642.firebasestorage.app',
    androidClientId: '572463722097-d6nbe4fnfn45ulfk5ier26bg5i8prblm.apps.googleusercontent.com',
    iosClientId: '572463722097-t2au0ipl4t6b6atcck2043pkm9agldau.apps.googleusercontent.com',
    iosBundleId: 'com.example.metApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtUiT2uaRBGflANIODgYEZFFGR8gotSzQ',
    appId: '1:572463722097:web:3e165bde4470100df4f5d0',
    messagingSenderId: '572463722097',
    projectId: 'metapp-b4642',
    authDomain: 'metapp-b4642.firebaseapp.com',
    storageBucket: 'metapp-b4642.firebasestorage.app',
    measurementId: 'G-GZP63B3PKE',
  );
}
